import type { StaticImageData } from "next/image";

import golfCharityShot from "@/public/golf-charity.png";
import licentraShot from "@/public/licentra.jpg";
import vocalsureShot from "@/public/vocalsure.png";

export type Project = {
  slug: string;
  title: string;
  subtitle: string;
  blurb: string;
  bullets: string[];
  stack: string[];
  period: string;
  /** `owner/name` — used to merge live GitHub metadata (pushed_at, language, stars). */
  repoFullName?: string;
  repo?: string;
  live?: string;
  /**
   * Statically imported so Next reads the intrinsic width/height at build time.
   * These are wide browser captures (2.4:1 and 1.9:1) and the card frames them
   * at their own ratio — nothing here should ever be cropped to fit a box.
   */
  image?: StaticImageData;
  featured: boolean;
  /** Drives the card's accent tint. */
  tone: "lime" | "cyan" | "violet";
};

/**
 * Featured projects use hand-written copy taken from the CV.
 * Live GitHub metadata is merged over these by `repoFullName` at request time —
 * see `mergeProjects` in lib/data.ts.
 */
export const projects: Project[] = [
  {
    slug: "vocalsure",
    title: "VocalSure",
    subtitle: "AI vs Human Voice Detection API",
    blurb:
      "A machine-learning API that decides whether a piece of audio was spoken by a human or generated by AI.",
    bullets: [
      "Designed and developed RESTful APIs for audio processing and prediction",
      "Implemented backend services for handling real-time requests",
      "Structured API endpoints following clean architecture principles",
      "Tested APIs against multiple datasets for performance validation",
    ],
    stack: ["Python", "Machine Learning", "REST API", "TypeScript"],
    period: "Feb 2026",
    repoFullName: "uv844/VocalSure-Echolyze",
    repo: "https://github.com/uv844/VocalSure-Echolyze",
    live: "https://studio--studio-7772900131-b7e6c.us-central1.hosted.app/",
    image: vocalsureShot,
    featured: true,
    tone: "lime",
  },
  {
    slug: "digital-heroes",
    title: "Digital Heroes",
    subtitle: "Golf Charity Subscription Platform",
    blurb:
      "A full-stack subscription platform where golfers track performance and enter monthly prize draws, with charity and admin operations built in.",
    bullets: [
      "Built a full-stack platform for performance tracking and monthly prize draws",
      "Integrated Supabase for authentication, database and real-time updates",
      "Implemented role-based access control across user and admin surfaces",
      "Designed responsive dashboards for subscriptions, winnings and analytics",
      "Shipped admin tooling to manage users, charities and draw operations",
    ],
    stack: ["React", "TypeScript", "Tailwind CSS", "Supabase", "PostgreSQL"],
    period: "Nov 2025",
    repoFullName: "uv844/Digital-heros-Golf-Charity",
    repo: "https://github.com/uv844/Digital-heros-Golf-Charity",
    live: "https://digital-heors-golf-charity.vercel.app/",
    image: golfCharityShot,
    featured: true,
    tone: "cyan",
  },
  {
    slug: "licentra",
    title: "Licentra",
    subtitle: "Software License Management System",
    blurb:
      "A C#/.NET platform for issuing, validating and tracking software licences across their lifecycle.",
    bullets: [
      "Licence issuing and validation flows built on .NET",
      "Tracks licence state and lifecycle across products and customers",
      "Built as a team project under the Licentra-Team organisation",
    ],
    stack: ["C#", ".NET"],
    period: "Aug 2026",
    repoFullName: "Licentra-Team/Licentra",
    repo: "https://github.com/Licentra-Team/Licentra",
    live: "https://licentra-git-app-fwd6b4geedcfcpd4.centralindia-01.azurewebsites.net/",
    /**
     * The app gates every route behind auth, so the sign-in screen is the whole
     * public surface — captured in the site's own dark theme.
     */
    image: licentraShot,
    featured: true,
    tone: "violet",
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
export const otherProjects = projects.filter((p) => !p.featured);
